service: mes-microservices-starter-template

provider:
  name: aws
  runtime: nodejs8.10

functions:
  postResult:
    handler: src/functions/postResult/framework/handler.handler
    events:
      - http:
          path: test-result
          method: post

  getNextUploadBatch:
    handler: src/functions/getNextUploadBatch/framework/handler.handler
    events:
      - http:
          path: test-result/upload
          method: get

  updateUploadStatus:
    handler: src/functions/updateUploadStatus/framework/handler.handler
    events:
      - http:
          path: test-result/{app-ref}/upload
          method: put

  searchResults:
    handler: src/functions/searchResults/framework/handler.handler
    events:
      - http:
          path: test-result
          method: get

  getResult:
    handler: src/functions/getResult/framework/handler.handler
    events:
      - http:
          path: test-result/{app-ref}/{staff-number}
          method: get

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-webpack
  - serverless-offline
